### PR TITLE
Move multi into its own package + upgrade CW

### LINKED ISSUE #189: Create an sg-multi-test package
Break `multi` into `app` and `module` and add to this package.

### PR DESCRIPTION
**Pull request by shanev**
Fixes #189

### CODE REVIEW

**Review by JakeHartnell — APPROVED** [review]

**Comment by shanev** [comment]
Get this error when trying to publish:
```
error[E0308]: mismatched types
   --> /Users/blockshane/.cargo/registry/src/github.com-1ecc6299db9ec823/cw-multi-test-0.12.1/src/wasm.rs:439:29
    |
439 |                       result: ContractResult::Ok(SubMsgExecutionResponse {
    |  _____________________________^
440 | |                         events: r.events.clone(),
441 | |                         data: r.data,
442 | |                     }),
    | |______________________^ expected enum `SubMsgResult`, found enum `ContractResult`
    |
    = note: expected enum `SubMsgResult`
               found enum `ContractResult<SubMsgExecutionResponse>`
```

**Comment by webmaster128** [comment]
The error is due to this breaking change: https://github.com/CosmWasm/cosmwasm/pull/1232 between 1.0.0-beta5 and 1.0.0-beta6. In that PR you see an addition to `MIGRATING.md` which shows how caller code has to be adapted.

This was integrated into cw-multi-test in https://github.com/CosmWasm/cw-plus/pull/672 and released as part of cw-plus 0.13. Upgrading cosmwasm-* to 1.0.0-beta6+ and cw-multi-test to 0.13.x probably is all you need.

**Comment by shanev** [comment]
```
error[E0599]: the method `execute` exists for struct `cw721_base::Cw721Contract<'_, cosmwasm_std::Empty, StargazeMsgWrapper>`, but its trait bounds were not satisfied
   --> contracts/sg721/src/contract.rs:100:30
    |
100 |     Sg721Contract::default().execute(deps, env, info, msg)
    |                              ^^^^^^^ method cannot be called on `cw721_base::Cw721Contract<'_, cosmwasm_std::Empty, StargazeMsgWrapper>` due to unsatisfied trait bounds
```

**Review by yubrew — COMMENTED** [review]
should marketplace also use sg-multi-test? maybe it's a new and separate issue.

**Comment by shanev** [comment]
> should marketplace also use sg-multi-test? maybe it's a new and separate issue.

Yup! Going to version and publish it as a crate (in a separate issue after this).

**Pull request merged**
